name: Release nuget package

on:
  push:
    tags: "v-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.201
    - name: Build
      run: dotnet build --configuration Release ./src /p:AssemblyVersion=${GITHUB_REF#refs/tags/v-}
    - name: Create the package
      run: dotnet pack --configuration Release src/Seq.App.Telegram /p:Version=${GITHUB_REF#refs/tags/client-}
    - name: Publish the package to GPR
      run: dotnet nuget push src/Seq.App.Telegram/bin/Release/*.nupkg -s https://f.feedz.io/lykkecorp/xmm/nuget/index.json -k ${{ secrets.FEEDZ_TOKEN }}
